server:
  port: 8083
  servlet:
    context-path: /myTest
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: myTest
  redis:
    host: 192.168.1.204
    port: 6379
swagger:
  title: 测试
